# Generated by Django 3.1.6 on 2021-02-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupancy',
            old_name='CurrentOccupany',
            new_name='CurrentOccupancy',
        ),
    ]
