# Generated by Django 3.1.6 on 2021-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210316_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open Doors'), ('CLOSE', 'Close Doors'), ('RESET', 'Reset Doors')], max_length=6)),
            ],
            options={
                'db_table': 'Doors',
                'get_latest_by': 'TimeStamp',
            },
        ),
    ]
