# Generated by Django 3.1.6 on 2021-04-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupancy',
            options={'get_latest_by': 'TimeStamp'},
        ),
    ]
